# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				panda = true
				axolotl = true
				bee = true
				egg = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				skeleton = true
				bat = true
				frog = true
				rabbit = true
				drowned = true
				experience_orb = true
				dolphin = true
				item = true
				turtle = true
				salmon = true
				ocelot = true
				furnace_minecart = true
				horse = true
				minecart = true
				ender_dragon = true
				glow_squid = true
				glow_item_frame = false
				squid = true
				parrot = true
				creeper = true
				enderman = true
				chicken = true
				tropical_fish = true
				chest_minecart = true
				fox = true
				slime = true
				pillager = true
				iron_golem = true
				zombified_piglin = true
				piglin = true
				cat = true
				zombie = true
				ghast = true
				sheep = true
				player = true
				pufferfish = true
				potion = true
				wolf = true
				villager = true
				tnt_minecart = true
				zombie_villager = true
				polar_bear = true
				strider = true
				cave_spider = true
				cod = true
				witch = true
				snow_golem = true
				spider = true

			[light_sources.settings.entities.tconstruct]
				flint_shuriken = true
				glow_ball = true
				earth_slime = true
				fancy_item_frame = true
				efln_ball = true

			[light_sources.settings.entities.xercapaint]
				easel = true

			[light_sources.settings.entities.earthtojavamobs]
				piebald_pig = true
				dairy_cow = true
				pink_footed_pig = true
				flecked_sheep = true
				cream_cow = true
				spotted_pig = true
				midnight_chicken = true
				skeleton_wolf = true
				rainbow_sheep = true
				gold_crested_chicken = true
				mottled_pig = true
				bold_striped_rabbit = true
				long_nosed_sheep = true
				freckled_rabbit = true
				muddy_pig = true
				amber_chicken = true
				bouldering_zombie = true
				sooty_pig = true
				patched_sheep = true
				bronzed_chicken = true
				melon_golem = true
				stormy_chicken = true
				horned_sheep = true
				harelequin_rabbit = true
				rocky_sheep = true
				cookie_cow = true
				pinto_cow = true
				fuzzy_sheep = true
				bone_spider = true
				cluckshroom = true
				albino_cow = true
				fancy_chicken = true
				jolly_llama = true
				inky_sheep = true
				tropical_slime = true
				sunset_cow = true
				skewbald_chicken = true
				pale_pig = true
				lobber_zombie = true

			[light_sources.settings.entities.artifacts]
				mimic = true

			[light_sources.settings.entities.gateofbabylon]
				yoyo = true
				boomerang = true

